# Generated by Django 5.0.4 on 2024-07-22 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_item_fathersname_item_gsisidno_item_mothersname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='placeOfBbirth',
            new_name='placeOfBirth',
        ),
    ]
